s3_conf:
  access_key: AKIAURNMC6NN2E3WCTC4
  secret_access_key: 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
  s3_bucket: subhayan-bucket

sftp_conf:
    hostname: xyz.amazonaws.com
    port: 22
    username: ubuntu
    pem: resources/sftpKeyPair.ppk
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data

mongodb_config:
  input.uri: mongodb://localhost:27017
  output.uri: mongodb://localhost:27017
  input.database: school
  database: school
  collection: students

redshift_conf:
  host: abc.com
  port: 5439
  database: testdb
  username: master
  password: uuuu
  filetype: csv
  delimiter: |

mysql_conf:
  hostname: abc.com
  port: 3306
  database: IRMSDB
  username: admin
  password: yui
